import type { ThemeFamily } from './types';

export const FAMILIES: ThemeFamily[] = [
  {
    index: '01',
    name: 'Stone',
    light: {
      id: 'light',
      accentHex: '#3a6cb5',
      tagline: 'Warm neutrals · Classic blue',
      preview: {
        bg: '#faf9f7',
        sidebar: '#f6f5f0',
        sidebarStrip: '#e8e3dc',
        sidebarActive: '#3a6cb5',
        card: '#ffffff',
        text: '#28221e',
        muted: '#9a8e86',
        textDim: '#c8c2bb',
        primary: '#3a6cb5',
        primaryFg: '#ffffff',
        border: '#e8e3dc',
        inputBg: '#f0ede8',
      },
    },
    dark: {
      id: 'dark',
      accentHex: '#6b96d9',
      tagline: 'Deep navy · Electric blue',
      preview: {
        bg: '#0e1220',
        sidebar: '#0f1422',
        sidebarStrip: '#1a2035',
        sidebarActive: '#6b96d9',
        card: '#131826',
        text: '#e8e6e0',
        muted: '#586480',
        textDim: '#2a3250',
        primary: '#6b96d9',
        primaryFg: '#0e1220',
        border: '#1f2540',
        inputBg: '#1a2035',
      },
    },
  },
  {
    index: '02',
    name: 'Forest',
    light: {
      id: 'forest-light',
      accentHex: '#2e7d4f',
      tagline: 'Sunlit canopy · Soft sage',
      preview: {
        bg: '#f0f8f2',
        sidebar: '#e2f0e6',
        sidebarStrip: '#c4dfcc',
        sidebarActive: '#2e7d4f',
        card: '#f8fef9',
        text: '#0d2210',
        muted: '#4e8060',
        textDim: '#c0dcca',
        primary: '#2e7d4f',
        primaryFg: '#ffffff',
        border: '#c0dcca',
        inputBg: '#d4eadb',
      },
    },
    dark: {
      id: 'forest',
      accentHex: '#4cbb6a',
      tagline: 'Deep canopy · Emerald glow',
      preview: {
        bg: '#0d1a12',
        sidebar: '#0f1e14',
        sidebarStrip: '#182a1c',
        sidebarActive: '#4cbb6a',
        card: '#111e16',
        text: '#deeee5',
        muted: '#5a8060',
        textDim: '#1c2e20',
        primary: '#4cbb6a',
        primaryFg: '#0d1a12',
        border: '#1c2e20',
        inputBg: '#172218',
      },
    },
  },
  {
    index: '03',
    name: 'Crimson',
    light: {
      id: 'crimson',
      accentHex: '#8b1a1a',
      tagline: 'Paper white · Deep burgundy',
      preview: {
        bg: '#faf8f5',
        sidebar: '#f5f2ed',
        sidebarStrip: '#ecddd8',
        sidebarActive: '#8b1a1a',
        card: '#fffefb',
        text: '#1e1610',
        muted: '#9a8070',
        textDim: '#e8ddd5',
        primary: '#8b1a1a',
        primaryFg: '#ffffff',
        border: '#e8ddd5',
        inputBg: '#f2ede8',
      },
    },
    dark: {
      id: 'crimson-dark',
      accentHex: '#d44040',
      tagline: 'Blood-red void · Glowing rose',
      preview: {
        bg: '#160c0c',
        sidebar: '#1a0e0e',
        sidebarStrip: '#2a1414',
        sidebarActive: '#d44040',
        card: '#1e1010',
        text: '#f0e4e4',
        muted: '#885050',
        textDim: '#2a1414',
        primary: '#d44040',
        primaryFg: '#160c0c',
        border: '#2a1414',
        inputBg: '#220f0f',
      },
    },
  },
  {
    index: '04',
    name: 'Amber',
    light: {
      id: 'amber',
      accentHex: '#b87e0a',
      tagline: 'Warm parchment · Molten gold',
      preview: {
        bg: '#f9f5e4',
        sidebar: '#f4eed6',
        sidebarStrip: '#e8ddb8',
        sidebarActive: '#b87e0a',
        card: '#fffcf0',
        text: '#1a1200',
        muted: '#8a7040',
        textDim: '#e5d8b0',
        primary: '#b87e0a',
        primaryFg: '#1a1200',
        border: '#e5d8b0',
        inputBg: '#eee4c0',
      },
    },
    dark: {
      id: 'amber-dark',
      accentHex: '#e8a020',
      tagline: 'Scorched earth · Liquid gold',
      preview: {
        bg: '#120d02',
        sidebar: '#160f04',
        sidebarStrip: '#241808',
        sidebarActive: '#e8a020',
        card: '#1a1005',
        text: '#f2e8cc',
        muted: '#8a7030',
        textDim: '#241808',
        primary: '#e8a020',
        primaryFg: '#120d02',
        border: '#241808',
        inputBg: '#1e1406',
      },
    },
  },
  {
    index: '05',
    name: 'Obsidian',
    light: {
      id: 'obsidian-light',
      accentHex: '#1a7a96',
      tagline: 'Arctic glass · Deep teal clarity',
      preview: {
        bg: '#f2f8fc',
        sidebar: '#e8f2f8',
        sidebarStrip: '#d0e6f2',
        sidebarActive: '#1a7a96',
        card: '#ffffff',
        text: '#0c1e28',
        muted: '#527a8a',
        textDim: '#c8dae8',
        primary: '#1a7a96',
        primaryFg: '#ffffff',
        border: '#c8dae8',
        inputBg: '#dceaf4',
      },
    },
    dark: {
      id: 'obsidian',
      accentHex: '#40d8f0',
      tagline: 'Pure black void · Cyan pulse',
      preview: {
        bg: '#09090f',
        sidebar: '#0b0b14',
        sidebarStrip: '#131320',
        sidebarActive: '#40d8f0',
        card: '#0d0d18',
        text: '#d0e0ee',
        muted: '#3a5060',
        textDim: '#16161f',
        primary: '#40d8f0',
        primaryFg: '#09090f',
        border: '#16161f',
        inputBg: '#111118',
      },
    },
  },
  {
    index: '06',
    name: 'Violet',
    light: {
      id: 'violet-light',
      accentHex: '#6b3db8',
      tagline: 'Pale lavender · Rich amethyst',
      preview: {
        bg: '#f5f3fc',
        sidebar: '#ede9f8',
        sidebarStrip: '#d8d0f2',
        sidebarActive: '#6b3db8',
        card: '#fdfcff',
        text: '#18073e',
        muted: '#7a6aa0',
        textDim: '#d8d0f2',
        primary: '#6b3db8',
        primaryFg: '#ffffff',
        border: '#d8d0f2',
        inputBg: '#e5e0f5',
      },
    },
    dark: {
      id: 'violet-dark',
      accentHex: '#9c68f0',
      tagline: 'Deep indigo void · Electric amethyst',
      preview: {
        bg: '#0e0918',
        sidebar: '#120d20',
        sidebarStrip: '#1c1630',
        sidebarActive: '#9c68f0',
        card: '#140f22',
        text: '#e2d8f8',
        muted: '#6040a0',
        textDim: '#1c1630',
        primary: '#9c68f0',
        primaryFg: '#0e0918',
        border: '#201a38',
        inputBg: '#18122c',
      },
    },
  },
];
